<?php
/**
 * @file
 * Code for the Facebook Comments Block module.
 */

/**
 * Implements hook_block_info().
 */
function facebook_comments_block_block_info() {
  $blocks = array();
  $blocks['fb_comments'] = array(
    'info' => t('Facebook Comments'),
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function facebook_comments_block_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'fb_comments':
      $form['facebook_comments_settings'] = array(
        '#type' => 'fieldset',
        '#title' => t('Facebook comments box settings'),
        '#description' => t('Configure facebook comments box.'),
        '#collapsible' => FALSE,
      );
      $form['facebook_comments_settings']['facebook_comments_block_settings_app_id'] = array(
        '#type' => 'textfield',
        '#title' => t('Facebook Application ID'),
        '#default_value' => variable_get('facebook_comments_block_settings_app_id', ''),
        '#maxlength' => 20,
        '#description' => t('Optional: Enter Facebook App ID.'),
        '#required' => FALSE,
      );
      $form['facebook_comments_settings']['facebook_comments_block_settings_color_schema'] = array(
        '#type' => 'select',
        '#title' => t('Color Scheme'),
        '#options' => array(
          'light' => t('Light'),
          'dark' => t('Dark'),
        ),
        '#default_value' => variable_get('facebook_comments_block_settings_color_schema', 'light'),
        '#description' => t('Set the color schema of facebook comments box.'),
        '#required' => TRUE,
      );
      $form['facebook_comments_settings']['facebook_comments_block_settings_number_of_posts'] = array(
        '#type' => 'textfield',
        '#title' => t('Number of posts'),
        '#default_value' => variable_get('facebook_comments_block_settings_number_of_posts', '5'),
        '#maxlength' => 1,
        '#description' => t('Select how many posts tou want to display by default.'),
        '#required' => TRUE,
      );
      $form['facebook_comments_settings']['facebook_comments_block_settings_width'] = array(
        '#type' => 'textfield',
        '#title' => t('Width'),
        '#default_value' => variable_get('facebook_comments_block_settings_width', '500'),
        '#maxlength' => 3,
        '#description' => t('Set width of facebook comments box.'),
        '#required' => TRUE,
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function facebook_comments_block_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'fb_comments':
      variable_set('facebook_comments_block_settings_app_id', $edit['facebook_comments_block_settings_app_id']);
      variable_set('facebook_comments_block_settings_color_schema', $edit['facebook_comments_block_settings_color_schema']);
      variable_set('facebook_comments_block_settings_width', $edit['facebook_comments_block_settings_width']);
      variable_set('facebook_comments_block_settings_number_of_posts', $edit['facebook_comments_block_settings_number_of_posts']);
      break;
  }
}

/**
 * Implements hook_theme().
 */
function facebook_comments_block_theme() {
  return array(
    'facebook_comments_block' => array(
      'template' => 'templates/facebook-comments-theme',
    ),
  );
}

/**
 * Implements hook_block_configure().
 */
function facebook_comments_block_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'fb_comments':
      $block = array(
        'subject' => t('Facebook comments'),
        'content' => theme('facebook_comments_block'),
      );
      break;
  }
  return $block;
}

/**
 * Processes variables for facebook_comments_block.tpl.php.
 *
 * The $variables array contains the following arguments:
 * - $url.
 * - $facebook_app_id.
 * - $facebook_app_id_script.
 * - $facebook_comments_block_settings_width.
 * - $facebook_comments_block_settings_number_of_posts.
 * - $facebook_comments_block_settings_color_schema.
 *
 * @see facebook_comments_block.tpl.php.
 */
function template_preprocess_facebook_comments_block(&$variables) {
  global $base_url;
  $url = $base_url . '/' . current_path();

  $facebook_app_id = variable_get('facebook_comments_block_settings_app_id', '');
  $facebook_app_id_script = (($facebook_app_id != '') ? "&appId=$facebook_app_id" : '') . '";';

  $variables['url'] = $url;
  $variables['facebook_app_id'] = $facebook_app_id;
  $variables['facebook_app_id_script'] = $facebook_app_id_script;
  $variables['facebook_comments_block_settings_width'] = variable_get('facebook_comments_block_settings_width', '500');
  $variables['facebook_comments_block_settings_number_of_posts'] = variable_get('facebook_comments_block_settings_number_of_posts', '5');
  $variables['facebook_comments_block_settings_color_schema'] = variable_get('facebook_comments_block_settings_color_schema', 'light');
}
